LAYOUTS = default
MCU = STM32F303

BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = lite
MOUSEKEY_ENABLE = no 
EXTRAKEY_ENABLE = yes 
CONSOLE_ENABLE = no  
COMMAND_ENABLE = no    
NKRO_ENABLE = yes     
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
TAP_DANCE_ENABLE = yes 
